# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: npm install
    - run: npm install -g codecov
    - run: npm run coverage
    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - run: echo "Run this only if merging to master - here there will be npm publish (see below)"
      if: github.ref == 'master'
    #- run: npm publish
    #  if: github.ref == 'master'
    #    with:
    #      token: ${{ secrets.NPM_TOKEN }}
